apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: stock-news
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      initContainers:
      - name: airflow-db-init
        image: apache/airflow:2.7.0
        command: ["airflow", "db", "migrate"]
        env:
        - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
          valueFrom:
            secretKeyRef:
              name: airflow-secrets
              key: sql-alchemy-conn
        - name: AIRFLOW__CORE__FERNET_KEY
          valueFrom:
            secretKeyRef:
              name: airflow-secrets
              key: fernet-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "0.25"
          limits:
            memory: "1Gi"
            cpu: "0.5"
        volumeMounts:
        - name: airflow-logs
          mountPath: /opt/airflow/logs
      containers:
      - name: airflow-scheduler
        image: apache/airflow:2.7.0
        command: ["/bin/bash", "-c"]
        args:
          - |
            airflow scheduler & 
            sleep 15 && airflow dags unpause stock_news_scheduler || true && 
            wait
        env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: "LocalExecutor"
        - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
          valueFrom:
            secretKeyRef:
              name: airflow-secrets
              key: sql-alchemy-conn
        - name: AIRFLOW__CORE__FERNET_KEY
          valueFrom:
            secretKeyRef:
              name: airflow-secrets
              key: fernet-key
        - name: AIRFLOW__WEBSERVER__SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: airflow-secrets
              key: webserver-secret-key
        - name: AIRFLOW__CORE__DAGS_FOLDER
          value: "/opt/airflow/dags"
        volumeMounts:
        - name: airflow-dags
          mountPath: /opt/airflow/dags/stock_news_scheduler.py
          subPath: stock_news_scheduler.py
        - name: airflow-logs
          mountPath: /opt/airflow/logs
        resources:
          requests:
            memory: "1Gi"
            cpu: "0.5"
          limits:
            memory: "2Gi"
            cpu: "1.0"
      volumes:
      - name: airflow-dags
        configMap:
          name: airflow-dags-config
          defaultMode: 0755
      - name: airflow-logs
        persistentVolumeClaim:
          claimName: airflow-logs-pvc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
  namespace: stock-news
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-webserver
  template:
    metadata:
      labels:
        app: airflow-webserver
    spec:
      containers:
      - name: airflow-webserver
        image: apache/airflow:2.7.0
        command: ["airflow", "webserver"]
        ports:
        - containerPort: 8080
        env:
        - name: AIRFLOW__WEBSERVER__BASE_URL
          value: "http://stock-news.local/airflow"
        - name: AIRFLOW__WEBSERVER__WEB_SERVER_URL_PREFIX
          value: "/airflow"
        - name: AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX
          value: "True"  
        - name: AIRFLOW__WEBSERVER__WEB_SERVER_HOST
          value: "0.0.0.0"
        - name: AIRFLOW__WEBSERVER__WEB_SERVER_PORT
          value: "8080"
        - name: AIRFLOW__CORE__EXECUTOR
          value: "LocalExecutor"
        - name: AIRFLOW__LOGGING__BASE_LOG_FOLDER
          value: "/opt/airflow/logs" 
        - name: AIRFLOW__CORE__BASE_LOG_FOLDER
          value: "/opt/airflow/logs"  
        - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
          valueFrom:
            secretKeyRef:
              name: airflow-secrets
              key: sql-alchemy-conn
        - name: AIRFLOW__CORE__FERNET_KEY
          valueFrom:
            secretKeyRef:
              name: airflow-secrets
              key: fernet-key
        - name: AIRFLOW__WEBSERVER__SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: airflow-secrets
              key: webserver-secret-key
        - name: AIRFLOW__CORE__DAGS_FOLDER
          value: "/opt/airflow/dags"
        volumeMounts:
        - name: airflow-dags
          mountPath: /opt/airflow/dags/stock_news_scheduler.py
          subPath: stock_news_scheduler.py
        - name: airflow-logs
          mountPath: /opt/airflow/logs
        resources:
          requests:
            memory: "1Gi"
            cpu: "0.5"
          limits:
            memory: "2Gi"
            cpu: "1.0"
      volumes:
      - name: airflow-dags
        configMap:
          name: airflow-dags-config
          defaultMode: 0755
      - name: airflow-logs
        persistentVolumeClaim:
          claimName: airflow-logs-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-logs-pvc
  namespace: stock-news
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 5Gi