apiVersion: apps/v1
kind: Deployment
metadata:
  name: company-service
  namespace: stock-news
spec:
  replicas: 2
  selector:
    matchLabels:
      app: company-service
  template:
    metadata:
      labels:
        app: company-service
    spec:
      initContainers:
      - name: setup-company-data
        image: tieudaochannhan/company-service:latest
        command: ["python", "setup_company.py"]
        env:
        - name: COMPANY_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: company-db-url
        - name: FMP_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: fmp-api-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "0.1"
          limits:
            memory: "512Mi"
            cpu: "0.5"
      containers:
      - name: company-service
        image: tieudaochannhan/company-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: COMPANY_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: company-db-url
        - name: FMP_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: fmp-api-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "0.25"
          limits:
            memory: "1Gi"
            cpu: "0.5"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
      restartPolicy: Always
