apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-service
  namespace: stock-news
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news-service
  template:
    metadata:
      labels:
        app: news-service
    spec:
      initContainers:
      - name: setup-news-sources
        image: tieudaochannhan/news-service:latest
        command: ["python", "setup_sample_sources.py"]
        env:
        - name: NEWS_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: news-db-url
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: gemini-api-key
        - name: RABBITMQ_URL
          valueFrom:
            secretKeyRef:
              name: queue-secrets
              key: rabbitmq-url
        resources:
          requests:
            memory: "256Mi"
            cpu: "0.1"
          limits:
            memory: "512Mi"
            cpu: "0.5"
      containers:
      - name: news-service
        image: tieudaochannhan/news-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: NEWS_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: news-db-url
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: gemini-api-key
        - name: RABBITMQ_URL
          valueFrom:
            secretKeyRef:
              name: queue-secrets
              key: rabbitmq-url
        resources:
          requests:
            memory: "512Mi"
            cpu: "0.5"
          limits:
            memory: "1Gi"
            cpu: "1.0"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
      restartPolicy: Always
