apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-storage
provisioner: nfs.csi.k8s.io
parameters:
  server: localhost
  share: /srv/nfs/k8s-storage
  mountPermissions: "0777"
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
